// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: check.proto

package checkclient

import (
	"context"

	"gozero-exp/rpc/check/check"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckReq  = check.CheckReq
	CheckResp = check.CheckResp

	Check interface {
		Check(ctx context.Context, in *CheckReq, opts ...grpc.CallOption) (*CheckResp, error)
	}

	defaultCheck struct {
		cli zrpc.Client
	}
)

func NewCheck(cli zrpc.Client) Check {
	return &defaultCheck{
		cli: cli,
	}
}

func (m *defaultCheck) Check(ctx context.Context, in *CheckReq, opts ...grpc.CallOption) (*CheckResp, error) {
	client := check.NewCheckClient(m.cli.Conn())
	return client.Check(ctx, in, opts...)
}
