// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: add.proto

package server

import (
	"context"

	"gozero-exp/rpc/add/add"
	"gozero-exp/rpc/add/internal/logic"
	"gozero-exp/rpc/add/internal/svc"
)

type AddServer struct {
	svcCtx *svc.ServiceContext
	add.UnimplementedAddServer
}

func NewAddServer(svcCtx *svc.ServiceContext) *AddServer {
	return &AddServer{
		svcCtx: svcCtx,
	}
}

func (s *AddServer) Add(ctx context.Context, in *add.AddReq) (*add.AddResp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}
