// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: add.proto

package addclient

import (
	"context"

	"gozero-exp/rpc/add/add"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddReq  = add.AddReq
	AddResp = add.AddResp

	Add interface {
		Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddResp, error)
	}

	defaultAdd struct {
		cli zrpc.Client
	}
)

func NewAdd(cli zrpc.Client) Add {
	return &defaultAdd{
		cli: cli,
	}
}

func (m *defaultAdd) Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddResp, error) {
	client := add.NewAddClient(m.cli.Conn())
	return client.Add(ctx, in, opts...)
}
